const typingText = document.querySelector(".typing-text p"),
timeTag = document.querySelector(".time span b"),
wpmTag = document.querySelector(".wpm span"),
cpmTag = document.querySelector(".cpm span"),
inputField = document.querySelector(".wrapper .input-field"),
mistakeTag = document.querySelector(".mistake span"),
tryAgainBtn = document.querySelector("button"),




par = [
    "Lorem ipsum, dolor sit amet conse adip elit. Sed labore tempore nobis harum esse facilis! Adipisci.Nostrum illo, velit odio ab placeat explicabo quisquam ipsum repellendus facilis, illum in. Facere ut minima perferendis? Dolores aut corporis vitae quos sunt quibusdam deserunt architecto quaerat libero impedit omnis, sapiente tempora placeat rerum perspiciatis rem explicabo quas eaque, blanditiis suscipit incidunt nulla. Natus, accusantium voluptatibus earum recusandae consequatur sunt! A sint nulla delectus doloremque beatae non omnis exercitationem quam nihil modi quaerat recusandae rerum explicabo sapiente, aspernatur accusantium commodi sequi vel rem molestias maiores ea tempora deleniti quisquam? Magni in est fugit ullam. Distinctio repudiandae officia hic, modi corporis illo assumenda perferendis minima amet porro aliquam placeat saepe necessitatibus id neque. Nam quos fugiat cupiditate quisquam in officia, vero, natus neque voluptate molestias voluptatibus velit? Veritatis, quam exercitationem harum eveniet repellat nam incidunt hic omnis fuga cum velit officiis autem, commodi asperiores ipsa iure esse atque perferendis explicabo quos laudantium ex dolore dolorem minus. Dolorem delectus neque quia ipsam cupiditate. Nulla ad fugit, beatae molestiae recusandae ducimus dolores? Cum enim.",
    "omnis a? Cupiditate fugit consequuntur iste incidunt repellat illum odit at nostrum pariatur maxime autem veritatis.unde magni voluptates delectus maiores quos porro fuga repellat, nisi, rerum placeat? Eos vel a rerum culpa qui quia minus nostrum, ab cumque laudantium non asperiores, deserunt voluptates doloremque incidunt, tenetur sit repudiandae velit odit! Dicta quam earum nisi modi explicabo sed aliquam excepturi incidunt corporis voluptatem, consequuntur accusantium, iure doloremque! Dolorem, incidunt numquam provident quos dolore eveniet voluptate dicta amet quia molestias! Perspiciatis quae repellendus vero corporis. At eligendi mollitia molestiae ipsum itaque numquam asperiores amet nobis quibusdam sapiente iste est eaque voluptatum officiis libero facere eum, suscipit illo debitis dolorum laborum, consectetur rerum a! Consequuntur eligendi temporibus officiis error enim esse illo dolores numquam, ducimus aliquam quibusdam autem ex nisi. Sed officia animi alias amet, voluptates est molestias voluptatem beatae cumque aliquam soluta. Cum voluptatum architecto neque provident voluptas, inventore explicabo porro, officia suscipit quos asperiores odit quam qui? Molestiae explicabo necessitatibus fuga, illo debitis magni, repellendus accusamus ipsa doloribus quasi nam labore maxime deserunt fugit?",
    "animi sunt dignissimos eaque, velit veniam quasi consectetur aut ex facere. Ipsum ut dolore mollitia expedita temporibus.incidunt dolorum itaque consectetur praesentium, corrupti suscipit sunt atque laboriosam deleniti harum molestiae sapiente sit nulla dolore delectus explicabo! Veritatis quasi vero reprehenderit tenetur illo ducimus illum inventore assumenda consequuntur. Ex quae hic fugit. Saepe ab consequuntur aliquam placeat nobis nulla eos perspiciatis quo quia quisquam corrupti, illum quibusdam perferendis rem! Ex molestias perspiciatis, culpa ab fuga possimus natus accusamus minima quasi! Dolores error iste eius. Repudiandae ab corrupti amet odit! Ducimus ullam est ipsa culpa totam quasi explicabo modi magnam velit dolores ipsam eum ",
    "quis, impedit error nemo fugiat qui sed dolor cupiditate animi, est doloremque tenetur tempora nostrum perspiciatis autem.distinctio, alias laboriosam, fuga amet voluptas optio corporis rem placeat odio blanditiis harum cumque in dolorem fugiat quis enim maiores sint! Fuga amet unde, perferendis est, quia odio veritatis culpa consequatur accusamus eligendi tempore dolorum eaque. Tempora consectetur libero rerum. Nisi, temporibus. Cum quos alias provident labore? Dicta nisi possimus repellat quisquam doloremque atque qui dignissimos voluptate! Provident ex nisi molestiae et obcaecati aliquid amet architecto mollitia? Nostrum laudantium deleniti culpa, ad molestias provident minus? Vel cumque aperiam iusto, tempore labore veritatis dignissimos eum obcaecati",
    "sunt molestias? Aperiam iusto incidunt magnam a nesciunt maiores odio earum reiciendis ipsum minus quidem veniam molestiae aliquid.dolorum sapiente, rem iste, quis corrupti tenetur repudiandae commodi ab aliquam similique voluptatum. Aperiam distinctio nihil repudiandae assumenda facere nobis quisquam, alias ea amet dignissimos non tempora cumque, dolore aut nulla eligendi dolor odit tenetur sit sunt ut itaque saepe dolorum! Perferendis culpa a voluptas necessitatibus tempore quis temporibus at repudiandae labore! Rem error architecto ut voluptatum vitae, a beatae ",
    "quisquam animi doloremque, reprehenderit perferendis sed, dolores inventore fuga quae delectus? Voluptatum laborum reiciendis, ullam.ducimus placeat dolores. Aliquam, quos dolor animi placeat vero magni. Voluptates repellendus corrupti obcaecati ex error necessitatibus fuga commodi animi hic saepe, ullam expedita nam perferendis voluptatibus impedit sit, sapiente ratione, beatae dignissimos non repudiandae. Molestias, repellat! Natus esse earum dolorum",
    "odit quae unde delectus sit exercitationem quo iusto aspernatur accusamus quia amet odio iure, quasi, dolorem quas ea ipsum consequuntur.labore, dolorum expedita aperiam debitis optio necessitatibus quam! Officia at ratione laudantium numquam commodi natus consequuntur tempore assumenda facere voluptatibus expedita quasi debitis alias, laborum illum aspernatur doloremque soluta odio sed. Delectus maxime, laboriosam unde, fugit labore inventore obcaecati quo ea quaerat itaque molestiae sequi? Neque incidunt voluptatum veritatis voluptatem, unde ipsam consequatur",
    "Quisquam hic, tempora necessitatibus corrupti id perferendis soluta veritatis maxime mollitia esse eligendi quae deserunt nisi. Sequi obcaecati.quos beatae vitae voluptate, sunt sequi, aut itaque, cum ducimus blanditiis commodi sint aliquid atque! Similique iure sint aliquid repellendus, qui inventore, laudantium architecto, nisi quibusdam officia sequi ipsam tempora. Officiis, ipsa. Voluptatem, nemo. Nulla soluta officia culpa asperiores consequuntur quod vero, earum consequatur itaque voluptates ipsa sed minus reprehenderit! Ipsum ratione aliquam repellendus",
    "perspiciatis non eligendi accusantium mollitia quaerat reprehenderit perferendis deserunt ab animi eaque ipsa quia expedita quidem doloribus voluptate.maiores corrupti soluta dignissimos! Fugiat non cumque pariatur nihil explicabo possimus et. Soluta temporibus laborum mollitia exercitationem fugiat magni saepe sapiente, vitae consequuntur error veritatis dolores. Fugit inventore enim asperiores nemo! Deserunt soluta, modi tenetur aut expedita numquam qui eveniet iure quas autem doloremque incidunt sed exercitationem accusantium alias magni? Totam, impedit amet. Veniam",
    "magnam facere quibusdam asperiores voluptatum, atque at? Quia dolores doloribus, aspernatur ipsa ab vitae in! Asperiores dolorem natus amet repellat.blanditiis cum incidunt optio illo numquam magni voluptas similique dolor minima quibusdam pariatur eveniet rem quis iusto libero. Distinctio quasi, exercitationem saepe est, commodi ipsa iure iusto tempora, voluptates illum culpa accusamus aliquam. Fugit animi reprehenderit veniam tempore deserunt nihil nisi commodi totam veniam! Facere voluptas unde accusamus obcaecati odio libero dolorum praesentium, minima tempora doloremque assumenda dolore. Et nemo consectetur, aliquam voluptas culpa delectus velit",
    "Asperiores, recusandae aliquam similique vero aliquid et blanditiis nostrum beatae excepturi quibusdam libero exercitationem quidem repudiandae! Veniam.vitae, quaerat cupiditate voluptatem reiciendis voluptate eius eligendi asperiores repellat quasi molestias mollitia quisquam animi nam, natus eaque architecto veniam ad aspernatur blanditiis! Illum id quaerat suscipit repudiandae neque natus atque sunt molestias necessitatibus ut? Rerum asperiores, unde, provident",
    "ratione aspernatur necessitatibus fuga, repudiandae facilis maxime? Commodi nihil hic, ipsa cupiditate tenetur possimus suscipit. Soluta nostrum rem, non.aperiam delectus enim? Enim, rem earum incidunt pariatur voluptas recusandae itaque minus architecto ipsam? Iusto autem labore, officia est esse ex earum voluptates! Est ad optio praesentium minima temporibus debitis quia, facilis deserunt accusamus voluptate labore necessitatibus unde earum soluta quos vero amet? Quos officiis animi vitae, repudiandae dolor rerum eaque sit repellat nam a delectus maxime magnam dolores, officia.",
    "amet qui ullam dolores exercitationem doloremque ab voluptate totam officiis esse iure dolorem, rerum id corrupti doloribus provident voluptas quasi nulla.suscipit iusto hic. Aspernatur beatae eaque quaerat soluta sint, perspiciatis id laudantium. Quidem ducimus distinctio ut tempora nostrum optio accusantium atque, nemo officiis cum facere? A cum tempore sit velit debitis laudantium incidunt libero iste tenetur voluptatem ullam consectetur, in itaque nulla quos laboriosam",
    "repudiandae eveniet. Odit ratione voluptatibus facilis officia magnam consectetur, cumque minima neque numquam voluptatem iusto eligendi. Iure in deserunt.laboriosam, nulla sapiente at ipsa ad maiores asperiores alias, voluptatem aliquid dolorum et dolor sint! Sapiente ut debitis voluptatum molestiae quod ab fugiat, facilis voluptates omnis nostrum totam. Natus sed, provident voluptate rem, nihil vero molestiae molestias magni, eos reiciendis modi corporis! Minima a deserunt",
    "praesentium nemo, sapiente odio eos fugit magnam ipsa quod placeat rerum tenetur repellendus dolore! Officiis, quam. Corporis obcaecati fugit, dolorum odit.Maxime tenetur ipsum repudiandae quasi ducimus. Earum soluta alias esse ut, maxime corrupti modi neque, eius voluptas, ex totam. Quasi tempore amet exercitationem. Vero doloremque dicta nemo at hic perspiciatis repellendus! Error amet architecto sapiente, inventore, iure at ipsa cumque voluptatem sit officia cupiditate cum saepe, aspernatur itaque maiores quibusdam vitae rerum? Blanditiis, autem iusto. Distinctio ducimus",
    "atque placeat mollitia libero minima cupiditate praesentium numquam eum modi sit quaerat optio inventore aperiam pariatur nesciunt sunt ea, similique at.facere asperiores enim reiciendis reprehenderit error quidem quam aperiam et aut nihil? Consequatur voluptates delectus, rerum debitis hic impedit rem laudantium necessitatibus sequi ullam, itaque beatae quo assumenda eius explicabo praesentium optio deleniti maxime excepturi ratione! Temporibus, quia. Soluta quos culpa ipsam mollitia corporis odit, obcaecati accusamus dolore, iure recusandae et nam rerum autem est?",
    "incidunt et perspiciatis. Suscipit at ducimus incidunt. Eaque velit necessitatibus possimus doloremque labore repellendus, amet vel, sit enim sunt, sequi est.temporibus excepturi blanditiis dignissimos pariatur in doloremque quibusdam, velit architecto similique aliquid consectetur quaerat voluptate reiciendis magnam sunt voluptatibus non nostrum hic! Sunt, tempore! Similique tempore aut sint, vero dolores numquam rerum neque ex voluptate incidunt natus dolore laboriosam quis nobis repudiandae culpa, mollitia voluptatem architecto at! Expedita magni, hic modi accusantium eum",
    "repudiandae eveniet. Odit ratione voluptatibus facilis officia magnam consectetur, cumque minima neque numquam voluptatem iusto eligendi. Iure in deserunt.optio perspiciatis, error consequatur excepturi, itaque ratione amet, id labore recusandae asperiores voluptas nisi hic? Minima, perferendis. Aliquid nihil quaerat omnis praesentium quibusdam necessitatibus excepturi dignissimos? Unde a nesciunt dolore? Reprehenderit cum nisi officiis ea illum labore est perspiciatis quis libero eveniet illo eaque fugit autem, cupiditate quos! Recusandae, maxime. Distinctio",
    "odit quae unde delectus sit exercitationem quo iusto aspernatur accusamus quia amet odio iure, quasi, dolorem quas ea ipsum consequuntur consequatur quia.delectus nihil nostrum hic reprehenderit commodi accusantium quas rerum voluptates. Eius natus perspiciatis autem commodi neque fugit odit nam deserunt fugiat, repellat porro praesentium quam temporibus doloribus excepturi velit reprehenderit. Similique ipsam repellat quam quo sit, doloremque inventore dolor, ab aliquid iure numquam eveniet amet eius, placeat a? Suscipit quaerat blanditiis excepturi ullam? Eligendi debitis",
    "adipisicing elit. Aut nam saepe debitis, itaque laborum, vero consectetur quasi maxime voluptate dolorem consequatur! Temporibus minima nam voluptas,blanditiis ratione! Vero reprehenderit tempora quidem veritatis maiores expedita ullam fugiat dolore iste exercitationem repellat magni libero, repudiandae voluptas. Iusto at nesciunt accusamus odit? Enim repudiandae saepe laboriosam, voluptas soluta in pariatur. Possimus, cum ullam voluptatem sequi, est nisi quo adipisci minus doloremque fuga sint harum, placeat temporibus ratione quasi? Veniam, tempore, dolores, obcaecati quidem nemo",
    "quis magni itaque perspiciatis ea dolore similique accusantium fuga voluptatum debitis nulla quidem hic, nihil illum praesentium vero quisquam dolorem ullam vitae.repellendus natus ab laudantium perferendis eos architecto non iusto aperiam voluptate? Voluptates labore blanditiis necessitatibus nam? Veritatis deserunt nam praesentium accusantium voluptates numquam pariatur, totam, quas at iste vero. Iusto ipsam fuga expedita, qui laboriosam sapiente culpa corporis. Magni iste architecto vitae ad dolorum et repellat, vero nam quas earum quidem velit expedita saepe, quia voluptate odit",
    "Accusantium repudiandae laboriosam consequuntur, molestias iste illo tempora porro? Beatae eum delectus repellendus saepe, dolore iure architecto incidunt facere perferendis deserunt quae molestiae rerum voluptatem numquam aliquam cumque possimus ullam aspernatur earum iure dignissimos quia, fuga eligendi tempore cum sit! Id, sint dolorum? Quam quisquam sequi soluta tempora sapiente suscipit dolores necessitatibus veniam officiis assumenda, tempore, architecto nemo error. Commodi beatae fuga, quos numquam error consequatur autem quae tempore debitis quibusdam ipsum ducimus modi",
    "voluptatibus quis ullam explicabo libero fugiat error? Unde fuga id quasi, ut quia porro obcaecati voluptas itaque fugiat necessitatibus amet optio esse nam natus voluptatibus consectetur recusandae porro consequuntur atque quam veniam, dolorem nobis eius ipsum illum natus, cum, commodi eos obcaecati minus facere omnis provident nulla et quasi? Sapiente tenetur magnam illum voluptas error esse quos laudantium neque architecto excepturi quis rerum autem porro cupiditate in qui sed quasi doloribus obcaecati, molestiae suscipit assumenda a voluptatem optio! Eveniet facere facilis assumenda fugit",
    "dolore ad libero quas voluptates dolores mollitia numquam! Quo odio rerum maxime nisi consequuntur doloremque itaque iure obcaecati sed asperiores sapiente sint consequatur, sunt blanditiis veniam quasi delectus? Obcaecati assumenda optio aut molestias magnam accusamus excepturi odit. Doloribus quae assumenda ab architecto corrupti odit laboriosam soluta aliquid non, iste tempore error. Corporis minus voluptate ipsa asperiores consequuntur ipsum quasi voluptates labore autem inventore odio eligendi nostrum aut nam fugiat impedit eius, expedita quaerat ex animi culpa. Sed quo unde rem odit",
    "porro cum unde optio voluptate dolorum doloribus quis ab! Voluptate, exercitationem magni consequatur nostrum nisi doloribus odio fuga ratione eos accusamus est libero eveniet autem corrupti velit, ex placeat consectetur quo molestiae tempora ratione blanditiis repellat, quaerat, asperiores eaque distinctio cumque natus? Voluptatum, facere! Nostrum, qui. Adipisci, eligendi ut molestias dolor eaque, quaerat non, accusantium veritatis labore soluta sunt voluptatibus magnam voluptate. Provident atque, nemo praesentium alias quidem itaque modi ratione repellendus quam expedita quas quos dignissimos laudantium magni",
    "obcaecati quasi molestias eum! Pariatur hic numquam ex cupiditate iste soluta ratione nobis esse consequatur, ipsum error aliquam magnam distinctio possimus, vitae quam! Delectus sapiente repellendus, velit error natus dolorum, maxime earum similique iure laboriosam non debitis mollitia quaerat vero maiores ipsum sint? Eligendi quam nulla facilis in reiciendis, labore saepe? Excepturi adipisci blanditiis, architecto rerum labore cum officia tenetur dolores dignissimos inventore eius laborum atque facilis ut ex vitae ratione culpa magni aut numquam beatae molestias cupiditate tempore autem? Id dolorum",
    "voluptatibus a illum aliquid deleniti. Animi repudiandae saepe aperiam explicabo vel cupiditate, unde, iure, commodi optio pariatur ullam soluta aliquam provident amet pariatur dolores magni, tempore reiciendis sit magnam optio modi mollitia distinctio quia ullam eius corporis possimus amet. Similique sequi quam inventore quae perferendis rerum magni est sapiente assumenda, beatae atque nam deleniti iste aperiam saepe distinctio? Exercitationem laudantium, enim sed nemo placeat cumque, maiores repellat veniam minus impedit consequatur autem tenetur ullam eos eius, minima sequi! Doloremque.",
    "Aspernatur laborum iusto, possimus sint adipisci facere debitis fugiat illum error, officiis suscipit ab accusamus aut! Nulla eaque eos, et commodi quaerat, asperiores voluptatem laborum illum totam doloremque officia quod temporibus facilis nihil quidem, repellat pariatur libero? Totam, assumenda! Culpa aliquam quaerat voluptatum, eveniet praesentium pariatur voluptatibus repellat deserunt doloremque, harum officia nisi fuga inventore dolorum iste est maxime officiis ducimus consectetur neque similique excepturi ipsum. Voluptatibus exercitationem soluta, a fuga odio assumenda similique sunt voluptates laborum vel dolorum, sit.",
    "veritatis cumque recusandae iusto tempora, corrupti nihil. Harum nobis ex eos consequuntur ut veritatis. Temporibus et iusto voluptatum repellat. Reiciendis deleniti, beatae consectetur incidunt facilis dolorum optio ex adipisci nesciunt, voluptatum quas eos praesentium, doloribus eligendi. Ea quibusdam, impedit modi similique dicta quas dolores sit culpa atque odit quae voluptatibus mollitia, autem eius, alias iure enim architecto ut ipsam iusto. Explicabo ipsum sapiente ratione culpa laborum! Perspiciatis cum numquam consequatur eius, consectetur ullam fugiat itaque nemo sequi officiis",
    "distinctio tenetur suscipit ipsum. Esse dolorum doloribus repellendus dicta, repudiandae quaerat cumque facere officiis consequatur doloremque possimus voluptatibus mollitia tempore dolorum cumque, sunt quibusdam adipisci voluptas? Perspiciatis quas ut quis molestias quo, harum non nemo beatae omnis neque ad alias obcaecati et. Placeat laborum quia illo molestiae inventore corrupti! Distinctio odio quo natus magni. Eveniet pariatur unde assumenda facilis a sequi quasi sunt nostrum totam. Maiores, totam! Iusto neque placeat atque a porro autem cupiditate molestiae amet nihil ipsam similique sed",
    "distinctio nemo voluptatem inventore ad minus odio iste reprehenderit! Consequatur esse sint eveniet laborum repellendus nesciunt cupiditate rerum aut deleniti iusto non delectus non nam expedita! Porro amet, nihil laborum, aspernatur cupiditate quia ipsum nesciunt sunt modi quae ducimus cum cumque iusto, vero magni! Nam, ea atque impedit corrupti sapiente obcaecati autem delectus fugiat alias placeat itaque perferendis accusantium adipisci nesciunt nemo est non minima error ipsum dolorem iste dicta. Esse repellendus autem accusantium quo earum a voluptates nemo illo facere assumenda ut eum aperiam eos",
    "nihil architecto sapiente vero nulla consequuntur eos facilis voluptatum! Itaque, id fugit voluptatibus ullam delectus aliquam recusandae omnis debitis optio alias ut maxime unde cumque Deserunt asperiores amet perspiciatis nostrum harum dicta laudantium, quasi eius. Ut architecto obcaecati dignissimos culpa repellat asperiores voluptate nesciunt quae cupiditate consequuntur ea aperiam ipsam, impedit eligendi officia accusantium qui cum dolorum vero mollitia praesentium. Provident, inventore! Eligendi culpa aliquam, illo consequatur ratione ducimus maxime excepturi optio commodi cupiditate assumenda",
    "Quia esse omnis nesciunt earum nam, inventore quod reprehenderit eos, quaerat tenetur repellendus quo ad. Commodi eos, quis quibusdam eligendi repudiandae quas voluptates officia? Dolores modi voluptatibus veritatis vitae, odio debitis repellat veniam nulla necessitatibus facere neque amet inventore temporibus adipisci. Facere tempora vel iusto recusandae laboriosam, est tempore neque. Iste unde voluptate, amet cum asperiores beatae minima omnis ab aliquam repudiandae perferendis? Fugiat nam, odit laboriosam debitis odio commodi eum eius modi tempora mollitia nisi accusamus voluptatibus doloribus soluta impedit?",
    "asperiores cumque molestias ea, laboriosam consequatur nihil odit numquam nam eos repellat vel, sequi aspernatur non ipsa? Laborum sequi, esse voluptatem ipsum illum omnis eligendi consectetur corrupti distinctio quidem accusantium minus autem. Corrupti magnam tempora ex quod voluptas natus necessitatibus qui dignissimos in esse maxime et nihil, ipsum consequatur obcaecati omnis aliquid voluptates. Et rem perspiciatis hic unde, minus doloremque cupiditate tempora esse exercitationem dicta sint ipsa accusamus velit dolore atque quidem voluptas neque, optio quo quisquam. Deserunt expedita autem animi tenetur.",
    "odit! Placeat nihil illo commodi, expedita, ex dicta reprehenderit, vel sequi magnam quaerat culpa quibusdam eligendi enim itaque possimus iste sit quia. Voluptatem rem aliquid ducimus ullam ratione inventore necessitatibus, labore qui omnis, ex minus quam quibusdam aliquam in eius reprehenderit. Incidunt voluptates laudantium dicta ea natus, harum exercitationem ducimus aspernatur dolorum placeat nobis consequatur quaerat accusamus labore. Distinctio facilis nemo exercitationem quae et. Aspernatur quam id impedit amet modi dolores laudantium maxime aliquid delectus a eligendi officiis totam voluptate, error, alias optio quis eius rem fugit.",
    "repellat nihil natus harum! Tempore ducimus nostrum officiis, hic nesciunt suscipit eius autem. Molestiae eligendi optio recusandae beatae minus nemo facere voluptatum tempora id dicta mollitia quaerat, laboriosam aut veniam quo? Accusantium asperiores at neque cupiditate deleniti. Ut, fugit? Debitis beatae deleniti repellat culpa numquam eveniet praesentium nisi dolorem, dolorum voluptatem ratione nesciunt alias dolores quasi, ipsam et aut, rerum veritatis mollitia exercitationem ducimus commodi! Ipsum molestiae corporis illum facere expedita itaque dolore voluptates quis officia ad consectetur maxime quos recusandae quia quidem. Facilis."
];
let timer,
maxTime = 60,
timeLeft = maxTime,
charIndex = mistakes = isTyping = 0;
function randomPar() {
    let randIndex = Math.floor(Math.random() * par.length);
    typingText.innerHTML = "";
    par[randIndex].split("").forEach(span => {
        let spanTag = `<span>${span}</span>`;
        typingText.innerHTML += spanTag;
    });
    typingText.querySelectorAll("span")[0].classList.add("active")
    document.addEventListener("keydown", () => inputField.focus());
    typingText.addEventListener("click", () => inputField.focus());
}
function initTyping() {
    const characters = typingText.querySelectorAll("span");
    let typedChar = inputField.value.split("")[charIndex];
    if(charIndex < characters.length - 1 && timeLeft > 0){
        if(!isTyping){
            timer = setInterval(initTimer, 1000)
            isTyping = true;
        }
        if(typedChar == null){
            charIndex--;
            if(characters[charIndex].classList.contains("incorrect")){
                mistakes--;
            }
            characters[charIndex].classList.remove("correct","incorrect");
        }else {
            if(characters[charIndex].innerText === typedChar) {
                characters[charIndex].classList.add("correct");
            } else {
                mistakes++;
                characters[charIndex].classList.add("incorrect");
            }
            charIndex++;
        }
        characters.forEach(span => span.classList.remove("active"));
        characters[charIndex].classList.add("active");
        
        let wpm = Math.round((((charIndex - mistakes) / 5) / (maxTime - timeLeft)) * 60);
        wpm = wpm < 0 || !wpm || wpm === Infinity ? 0 : wpm;
        mistakeTag.innerText = mistakes;
        wpmTag.innerText = wpm;
        cpmTag.innerText = charIndex - mistakes;
    }else{
        inputField.value = "";
        clearInterval(timer);
    }
}

function initTimer(){
    if(timeLeft > 0){
        timeLeft--;
        timeTag.innerText = timeLeft;
    } else {
        clearInterval(timer)
    }
}
function resetGame(){
    randomPar();
    timeLeft = maxTime,
    inputField.value = "";
    clearInterval(timer);
    charIndex = mistakes = isTyping = 0;
    timeTag.innerText = timeLeft;
    mistakeTag.innerText = mistakes;
    wpmTag.innerText = 0;
    cpmTag.innerText = 0;
}

randomPar();
inputField.addEventListener("input", initTyping);
tryAgainBtn.addEventListener("click", resetGame);
